### ISSUE TITLE
Use as submodule?

### ISSUE THREAD

**Issue by estahn** [bechtoldt/saltstack-elasticsearch-formula#8]
Hi @bechtoldt,

I can't quite figure out how to use this formula directly from the repository. I usually just checkout the formula from the repository and link it in the master, e.g.

```
file_roots:
  base:
    ...

  development:
    - /srv/formulas/php-formula
    - /srv/formulas/nginx-formula
    ...
    - /srv/formulas/elasticsearch-formula
```

Since your states are in the states directory this doesn't quite work.

Any tips?
