### ISSUE TITLE
Problem with deployment after formula name change

### ISSUE THREAD

**Issue by fir3wall** [bechtoldt/saltstack-elasticsearch-formula#9]
Hello

First of all great job with formula - really useful. I need to deploy it using different name (not elasticsearch) - I've included your formula in my (dion-analytics) under elasticsearch.sls file and I'm getting strange error, not sure is it caused by my error or renaming formula
## `

```
      ID: elasticsearch_config_main
Function: file.managed
    Name: /etc/elasticsearch/elasticsearch.yml
  Result: False
 Comment: Unable to manage file: Jinja syntax error: unexpected char u'&' at 30072; line 453

          ---
          [...]

            <div class="blob-wrapper data type-text">
                <table class="highlight tab-size js-file-line-container" data-tab-size="8">
                <tr>
                  <td id="L1" class="blob-num js-line-number" data-line-number="1"></td>
                  <td id="LC1" class="blob-code blob-code-inner js-file-line">{%- if datamap.config.main.format|default(&#39;YAML&#39;) == &#39;YAML&#39; -%}</td>    <======================
                </tr>
                <tr>
                  <td id="L2" class="blob-num js-line-number" data-line-number="2"></td>
                  <td id="LC2" class="blob-code blob-code-inner js-file-line">  {{- datamap.settings|default({})|yaml(False) -}}</td>
                </tr>
          [...]
          ---
 Started: 10:47:36.549927
Duration: 28.887 ms
 Changes:   
```

---

```
      ID: elasticsearch
Function: service.running
  Result: False
 Comment: One or more requisite failed: dion-analytics.elasticsearch.elasticsearch_config_main
 Started: 
Duration: 
 Changes:   
```

`
This is my common file: http://pastebin.com/BPcVX1eF
And this is my elasticsearch.sls file: http://pastebin.com/xFuvyPYe
Login / main files under files/ are the same as your version control.

In my plilar I'm just calling dion-analytics.elasticsearch: { }

Any ideas?
